
import React, { useState } from 'react';
import { AnalysisResult, RiskLevel } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { AlertTriangle, CheckCircle, FileText, Activity, Download, Zap, Database, Server, Box, Cpu } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface DashboardProps {
  results: AnalysisResult[];
}

const COLORS = ['#10B981', '#F59E0B', '#EF4444', '#7F1D1D']; 

const Dashboard: React.FC<DashboardProps> = ({ results }) => {
  const [isSimulatingJob, setIsSimulatingJob] = useState(false);

  const totalScans = results.length;
  const criticalIssues = results.filter(r => r.overallRisk === RiskLevel.CRITICAL || r.overallRisk === RiskLevel.HIGH).length;
  const avgScore = totalScans > 0 ? Math.round(results.reduce((acc, curr) => acc + curr.score, 0) / totalScans) : 100;

  const riskDistribution = [
    { name: 'Low', value: results.filter(r => r.overallRisk === RiskLevel.LOW).length },
    { name: 'Medium', value: results.filter(r => r.overallRisk === RiskLevel.MEDIUM).length },
    { name: 'High', value: results.filter(r => r.overallRisk === RiskLevel.HIGH).length },
    { name: 'Critical', value: results.filter(r => r.overallRisk === RiskLevel.CRITICAL).length },
  ].filter(d => d.value > 0);

  const trendData = results.length > 0 
    ? [...results].reverse().map((r, i) => ({ name: `Scan ${i+1}`, score: r.score }))
    : [
      { name: 'Mon', score: 95 },
      { name: 'Tue', score: 88 },
      { name: 'Wed', score: 92 },
      { name: 'Thu', score: 85 },
      { name: 'Fri', score: 98 },
    ];

  const handleSimulateJob = () => {
    setIsSimulatingJob(true);
    setTimeout(() => {
        setIsSimulatingJob(false);
        alert("Cloud Scheduler Job Executed: Nightly Risk Re-evaluation Complete. Trends updated in BigQuery.");
    }, 2000);
  };

  const handleDownloadReport = () => {
    if (results.length === 0) {
      alert("No analysis data available to generate a report.");
      return;
    }
    const latestResult = results[0];
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); 
    doc.text("Compliance Analysis Report", 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); 
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 30);
    doc.text(`Evidence ID: ${latestResult.id}`, 20, 35);
    
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Executive Summary", 20, 50);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Overall Risk Level:`, 20, 60);
    doc.text(latestResult.overallRisk, 60, 60);
    
    doc.text(`Compliance Score:`, 20, 68);
    doc.text(`${latestResult.score}/100`, 60, 68);
    
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const splitSummary = doc.splitTextToSize(latestResult.summary, 170);
    doc.text(splitSummary, 20, 80);

    let yPos = 80 + (splitSummary.length * 5) + 15;

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Detected Violations & Recommendations", 20, yPos);
    yPos += 10;

    if (latestResult.violations.length === 0) {
        doc.setFontSize(11);
        doc.setTextColor(22, 163, 74); 
        doc.text("No violations detected. Good job!", 20, yPos);
    } else {
        latestResult.violations.forEach((v, index) => {
            if (yPos > 260) {
                doc.addPage();
                yPos = 20;
            }
            doc.setFontSize(11);
            doc.setTextColor(185, 28, 28); 
            doc.text(`${index + 1}. Violation [${v.severity}]`, 20, yPos);
            yPos += 6;
            doc.setFontSize(10);
            doc.setTextColor(15, 23, 42);
            const desc = doc.splitTextToSize(v.description, 170);
            doc.text(desc, 20, yPos);
            yPos += (desc.length * 5) + 4;
            doc.setTextColor(71, 85, 105);
            doc.setFont(undefined, 'bold');
            doc.text("Recommendation:", 20, yPos);
            doc.setFont(undefined, 'normal');
            const rec = doc.splitTextToSize(v.recommendation, 135);
            doc.text(rec, 55, yPos);
            yPos += (rec.length * 5) + 10;
        });
    }
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by AI Compliance Copilot", 105, 290, { align: 'center' });
    doc.save(`compliance-report-${latestResult.id}.pdf`);
  };

  return (
    <div className="p-8 space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Compliance Overview</h1>
          <p className="text-slate-500 mt-2">Real-time insights from your automated compliance agent.</p>
        </div>
        <div className="flex gap-3">
            <button 
                onClick={handleSimulateJob}
                disabled={isSimulatingJob}
                className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2.5 rounded-lg flex items-center shadow-md transition-all text-sm font-medium"
            >
                <Zap className={`w-4 h-4 mr-2 ${isSimulatingJob ? 'animate-pulse text-yellow-400' : 'text-yellow-400'}`} />
                {isSimulatingJob ? 'Running Job...' : 'Simulate Nightly Audit'}
            </button>
            <button 
                onClick={handleDownloadReport}
                disabled={results.length === 0}
                className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-5 py-2.5 rounded-lg flex items-center shadow-md transition-all hover:shadow-lg"
            >
                <Download className="w-4 h-4 mr-2" />
                Download Report
            </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <StatCard title="Compliance Score" value={`${avgScore}%`} icon={Activity} color="text-blue-600" bgColor="bg-blue-50" />
        <StatCard title="Total Scans" value={totalScans.toString()} icon={FileText} color="text-indigo-600" bgColor="bg-indigo-50" />
        <StatCard title="Critical Risks" value={criticalIssues.toString()} icon={AlertTriangle} color="text-red-600" bgColor="bg-red-50" />
        <StatCard title="Audits Passed" value={`${totalScans - criticalIssues}`} icon={CheckCircle} color="text-green-600" bgColor="bg-green-50" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <h3 className="text-lg font-semibold text-slate-800 mb-4">Compliance Trend (7 Days)</h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis dataKey="name" stroke="#64748b" />
                <YAxis stroke="#64748b" domain={[0, 100]} />
                <Tooltip contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: '8px', color: '#fff' }} />
                <Line type="monotone" dataKey="score" stroke="#2563eb" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 8 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <h3 className="text-lg font-semibold text-slate-800 mb-4">Risk Distribution</h3>
          <div className="h-64 w-full flex items-center justify-center">
             {riskDistribution.length === 0 ? (
               <p className="text-slate-400">No data available yet</p>
             ) : (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={riskDistribution} cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="value">
                    {riskDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
             )}
          </div>
          <div className="flex justify-center gap-4 mt-4">
            {riskDistribution.map((entry, index) => (
              <div key={entry.name} className="flex items-center text-sm text-slate-600">
                <div className="w-3 h-3 rounded-full mr-2" style={{ backgroundColor: COLORS[index % COLORS.length] }}></div>
                {entry.name}
              </div>
            ))}
          </div>
        </div>
      </div>
      
       {/* Reference Architecture Visualization Panel */}
       <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-200">
            <div className="flex items-center gap-3 mb-6">
                <div className="bg-slate-100 p-2 rounded-lg">
                    <Server className="w-6 h-6 text-slate-700" />
                </div>
                <div>
                    <h3 className="text-lg font-bold text-slate-900">Core Architecture Summary</h3>
                    <p className="text-xs text-slate-500">Live visualization of the deployed Reference Architecture.</p>
                </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                 
                 {/* 1. App Layer */}
                 <div className="border border-indigo-100 bg-indigo-50/50 p-4 rounded-xl relative overflow-hidden group">
                     <div className="absolute top-0 right-0 p-2 opacity-10 group-hover:opacity-20 transition-opacity">
                         <Cpu className="w-16 h-16 text-indigo-600" />
                     </div>
                     <h4 className="font-bold text-indigo-900 text-sm mb-2 flex items-center">
                        <Box className="w-4 h-4 mr-2" /> Application Layer
                     </h4>
                     <ul className="text-xs text-indigo-800 space-y-1.5 ml-1">
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></div>Cloud Run (Scalable)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></div>Firebase Auth</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></div>React Frontend</li>
                     </ul>
                 </div>

                 {/* 2. Orchestration Layer */}
                 <div className="border border-blue-100 bg-blue-50/50 p-4 rounded-xl relative overflow-hidden group">
                     <div className="absolute top-0 right-0 p-2 opacity-10 group-hover:opacity-20 transition-opacity">
                         <Activity className="w-16 h-16 text-blue-600" />
                     </div>
                     <h4 className="font-bold text-blue-900 text-sm mb-2 flex items-center">
                        <Zap className="w-4 h-4 mr-2" /> Core Orchestration
                     </h4>
                     <ul className="text-xs text-blue-800 space-y-1.5 ml-1">
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-blue-500 rounded-full mr-2"></div>MCP Toolbox (Data Abstraction)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-blue-500 rounded-full mr-2"></div>ADK Agents (Python)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-blue-500 rounded-full mr-2"></div>Task Router</li>
                     </ul>
                 </div>

                 {/* 3. Hybrid Data Layer (Polyglot) */}
                 <div className="border border-emerald-100 bg-emerald-50/50 p-4 rounded-xl relative overflow-hidden group">
                     <div className="absolute top-0 right-0 p-2 opacity-10 group-hover:opacity-20 transition-opacity">
                         <Database className="w-16 h-16 text-emerald-600" />
                     </div>
                     <h4 className="font-bold text-emerald-900 text-sm mb-2 flex items-center">
                        <Server className="w-4 h-4 mr-2" /> Hybrid Data Layer
                     </h4>
                     <ul className="text-xs text-emerald-800 space-y-1.5 ml-1">
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full mr-2"></div>MongoDB Atlas (Vector Search)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full mr-2"></div>Spanner (Metadata)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full mr-2"></div>SQL (Generic)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full mr-2"></div>BigQuery (Analytics)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full mr-2"></div>Cloud Storage (Files)</li>
                     </ul>
                 </div>

                 {/* 4. AI Context Layer */}
                 <div className="border border-purple-100 bg-purple-50/50 p-4 rounded-xl relative overflow-hidden group">
                     <div className="absolute top-0 right-0 p-2 opacity-10 group-hover:opacity-20 transition-opacity">
                         <CheckCircle className="w-16 h-16 text-purple-600" />
                     </div>
                     <h4 className="font-bold text-purple-900 text-sm mb-2 flex items-center">
                        <Zap className="w-4 h-4 mr-2" /> AI & Context
                     </h4>
                     <ul className="text-xs text-purple-800 space-y-1.5 ml-1">
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-purple-500 rounded-full mr-2"></div>Gemini 2.5 (Multimodal)</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-purple-500 rounded-full mr-2"></div>Safety Guardrails</li>
                         <li className="flex items-center"><div className="w-1.5 h-1.5 bg-purple-500 rounded-full mr-2"></div>Google Search Grounding</li>
                     </ul>
                 </div>

            </div>
       </div>
    </div>
  );
};

const StatCard: React.FC<{ title: string; value: string; icon: any; color: string; bgColor: string }> = ({ title, value, icon: Icon, color, bgColor }) => (
  <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:shadow-md transition-shadow">
    <div className="flex items-center justify-between">
      <div>
        <p className="text-sm font-medium text-slate-500">{title}</p>
        <h2 className="text-3xl font-bold text-slate-900 mt-1">{value}</h2>
      </div>
      <div className={`p-3 rounded-lg ${bgColor} ${color}`}>
        <Icon size={24} />
      </div>
    </div>
  </div>
);

export default Dashboard;
