
import React, { useState } from 'react';
import { AnalysisResult, RiskLevel } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { AlertTriangle, CheckCircle, FileText, Activity, Download, Zap, Database, Server, Box, Cpu, PieChart as PieChartIcon } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface DashboardProps {
  results: AnalysisResult[];
}

const COLORS = ['#10B981', '#F59E0B', '#EF4444', '#7F1D1D']; 

const Dashboard: React.FC<DashboardProps> = ({ results }) => {
  const [isSimulatingJob, setIsSimulatingJob] = useState(false);

  const totalScans = results.length;
  const criticalIssues = results.filter(r => r.overallRisk === RiskLevel.CRITICAL || r.overallRisk === RiskLevel.HIGH).length;
  const avgScore = totalScans > 0 ? Math.round(results.reduce((acc, curr) => acc + curr.score, 0) / totalScans) : 100;

  const riskDistribution = [
    { name: 'Low', value: results.filter(r => r.overallRisk === RiskLevel.LOW).length },
    { name: 'Medium', value: results.filter(r => r.overallRisk === RiskLevel.MEDIUM).length },
    { name: 'High', value: results.filter(r => r.overallRisk === RiskLevel.HIGH).length },
    { name: 'Critical', value: results.filter(r => r.overallRisk === RiskLevel.CRITICAL).length },
  ].filter(d => d.value > 0);

  const trendData = results.length > 0 
    ? [...results].reverse().map((r, i) => ({ name: `Scan ${i+1}`, score: r.score }))
    : [
      { name: 'Mon', score: 95 },
      { name: 'Tue', score: 88 },
      { name: 'Wed', score: 92 },
      { name: 'Thu', score: 85 },
      { name: 'Fri', score: 98 },
    ];

  const handleSimulateJob = () => {
    setIsSimulatingJob(true);
    setTimeout(() => {
        setIsSimulatingJob(false);
        alert("Cloud Scheduler Job Executed: Nightly Risk Re-evaluation Complete. Trends updated in BigQuery.");
    }, 2000);
  };

  const handleDownloadReport = () => {
    if (results.length === 0) {
      alert("No analysis data available to generate a report.");
      return;
    }
    const latestResult = results[0];
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); 
    doc.text("Compliance Analysis Report", 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); 
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 30);
    doc.text(`Evidence ID: ${latestResult.id}`, 20, 35);
    
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Executive Summary", 20, 50);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Overall Risk Level:`, 20, 60);
    doc.text(latestResult.overallRisk, 60, 60);
    
    doc.text(`Compliance Score:`, 20, 68);
    doc.text(`${latestResult.score}/100`, 60, 68);
    
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const splitSummary = doc.splitTextToSize(latestResult.summary, 170);
    doc.text(splitSummary, 20, 80);

    let yPos = 80 + (splitSummary.length * 5) + 15;

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Detected Violations & Recommendations", 20, yPos);
    yPos += 10;

    if (latestResult.violations.length === 0) {
        doc.setFontSize(11);
        doc.setTextColor(22, 163, 74); 
        doc.text("No violations detected. Good job!", 20, yPos);
    } else {
        latestResult.violations.forEach((v, index) => {
            if (yPos > 260) {
                doc.addPage();
                yPos = 20;
            }
            doc.setFontSize(11);
            doc.setTextColor(185, 28, 28); 
            doc.text(`${index + 1}. Violation [${v.severity}]`, 20, yPos);
            yPos += 6;
            doc.setFontSize(10);
            doc.setTextColor(15, 23, 42);
            const desc = doc.splitTextToSize(v.description, 170);
            doc.text(desc, 20, yPos);
            yPos += (desc.length * 5) + 4;
            doc.setTextColor(71, 85, 105);
            doc.setFont(undefined, 'bold');
            doc.text("Recommendation:", 20, yPos);
            doc.setFont(undefined, 'normal');
            const rec = doc.splitTextToSize(v.recommendation, 135);
            doc.text(rec, 55, yPos);
            yPos += (rec.length * 5) + 10;
        });
    }
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by AI Compliance Copilot", 105, 290, { align: 'center' });
    doc.save(`compliance-report-${latestResult.id}.pdf`);
  };

  return (
    <div className="space-y-10 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 pb-6 border-b border-slate-200/60 dark:border-slate-800/60">
        <div>
          <h1 className="text-4xl font-display font-medium text-slate-900 dark:text-white tracking-tight">System Overview</h1>
          <p className="text-slate-500 dark:text-slate-400 mt-2 text-sm max-w-2xl">Real-time telemetry and compliance insights from the continuous evaluation engine.</p>
        </div>
        <div className="flex gap-3">
            <button 
                onClick={handleSimulateJob}
                disabled={isSimulatingJob}
                className="bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 px-5 py-2.5 rounded-xl flex items-center transition-all text-sm font-medium border border-slate-200/50 dark:border-slate-700/50"
            >
                <Zap className={`w-4 h-4 mr-2.5 ${isSimulatingJob ? 'animate-pulse text-amber-500' : 'text-slate-500 dark:text-slate-400'}`} />
                {isSimulatingJob ? 'Executing Job...' : 'Force Evaluation'}
            </button>
            <button 
                onClick={handleDownloadReport}
                disabled={results.length === 0}
                className="bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-5 py-2.5 rounded-xl flex items-center transition-all shadow-sm hover:shadow-indigo-500/20 text-sm font-medium"
            >
                <Download className="w-4 h-4 mr-2.5" />
                Export Ledger
            </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <StatCard title="Compliance Score" value={`${avgScore}%`} icon={Activity} color="text-indigo-600 dark:text-indigo-400" bgColor="bg-indigo-50 dark:bg-indigo-500/10" border="border-indigo-100 dark:border-indigo-500/20" />
        <StatCard title="Total Audits" value={totalScans.toString()} icon={FileText} color="text-emerald-600 dark:text-emerald-400" bgColor="bg-emerald-50 dark:bg-emerald-500/10" border="border-emerald-100 dark:border-emerald-500/20"/>
        <StatCard title="Critical Exposures" value={criticalIssues.toString()} icon={AlertTriangle} color="text-rose-600 dark:text-rose-400" bgColor="bg-rose-50 dark:bg-rose-500/10" border="border-rose-100 dark:border-rose-500/20"/>
        <StatCard title="Clear Nodes" value={`${totalScans - criticalIssues}`} icon={CheckCircle} color="text-slate-600 dark:text-slate-400" bgColor="bg-slate-100 dark:bg-slate-800" border="border-slate-200 dark:border-slate-700/50"/>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white dark:bg-slate-900/50 p-8 rounded-2xl border border-slate-200/60 dark:border-slate-800/60">
          <h3 className="text-sm font-semibold text-slate-800 dark:text-slate-200 mb-6 flex items-center uppercase tracking-widest"><Activity className="w-4 h-4 mr-2 text-indigo-500" /> Compliance Trend</h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#94a3b8" domain={[0, 100]} fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '12px', color: '#f8fafc', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }} />
                <Line type="stepAfter" dataKey="score" stroke="#4f46e5" strokeWidth={2} dot={{ r: 4, fill: '#4f46e5', strokeWidth: 2, stroke: '#fff' }} activeDot={{ r: 6, strokeWidth: 0 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900/50 p-8 rounded-2xl border border-slate-200/60 dark:border-slate-800/60">
          <h3 className="text-sm font-semibold text-slate-800 dark:text-slate-200 mb-6 flex items-center uppercase tracking-widest"><PieChartIcon className="w-4 h-4 mr-2 text-indigo-500" /> Risk Distribution</h3>
          <div className="h-56 w-full flex items-center justify-center">
             {riskDistribution.length === 0 ? (
               <p className="text-slate-400 font-mono text-sm">No telemetry available.</p>
             ) : (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={riskDistribution} cx="50%" cy="50%" innerRadius={70} outerRadius={90} paddingAngle={2} dataKey="value" stroke="none">
                    {riskDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: 'none', borderRadius: '8px', color: '#fff' }} itemStyle={{ color: '#fff' }} />
                </PieChart>
              </ResponsiveContainer>
             )}
          </div>
          <div className="flex justify-center gap-6 mt-6">
            {riskDistribution.map((entry, index) => (
              <div key={entry.name} className="flex items-center text-xs font-medium text-slate-600 dark:text-slate-400 bg-slate-50 dark:bg-slate-800 px-3 py-1.5 rounded-full">
                <div className="w-2 h-2 rounded-full mr-2" style={{ backgroundColor: COLORS[index % COLORS.length] }}></div>
                {entry.name}
              </div>
            ))}
          </div>
        </div>
      </div>
      
      <div className="bg-white dark:bg-slate-900/50 p-8 rounded-2xl border border-slate-200/60 dark:border-slate-800/60 mb-8 mt-8">
        <h3 className="text-sm font-semibold text-slate-800 dark:text-slate-200 mb-6 flex items-center uppercase tracking-widest"><FileText className="w-4 h-4 mr-2 text-indigo-500" /> Historical Audits</h3>
        {results.length === 0 ? (
          <p className="text-slate-400 font-mono text-sm">No audits recorded yet.</p>
        ) : (
          <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2">
            {results.map((result, idx) => (
              <div key={result.id || idx} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-100 dark:border-slate-700/50 gap-4">
                <div className="flex items-start gap-4 flex-1">
                  <div className={`mt-1 p-2 rounded-full flex-shrink-0 ${result.overallRisk === RiskLevel.CRITICAL || result.overallRisk === RiskLevel.HIGH ? 'bg-rose-100 dark:bg-rose-500/20 text-rose-600 dark:text-rose-400' : 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400'}`}>
                    {result.overallRisk === RiskLevel.CRITICAL || result.overallRisk === RiskLevel.HIGH ? <AlertTriangle className="w-5 h-5" /> : <CheckCircle className="w-5 h-5" />}
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-slate-900 dark:text-white flex items-center gap-2">
                       Audit #{totalScans - idx}
                       <span className={`text-[10px] px-2 py-0.5 rounded-full uppercase tracking-wider font-bold ${result.overallRisk === RiskLevel.CRITICAL || result.overallRisk === RiskLevel.HIGH ? 'bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-400' : 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'}`}>
                           {result.overallRisk === RiskLevel.CRITICAL || result.overallRisk === RiskLevel.HIGH ? 'Fail' : 'Pass'}
                       </span>
                    </h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 line-clamp-2">{result.summary || "No anomalies detected."}</p>
                  </div>
                </div>
                <div className="text-left sm:text-right whitespace-nowrap flex-shrink-0">
                  <p className="text-xs font-mono text-slate-500 dark:text-slate-400">{new Date(result.timestamp).toLocaleString()}</p>
                  <p className="text-sm font-bold text-slate-700 dark:text-slate-300 mt-1">Score: {result.score}/100</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
      
       {/* Reference Architecture Visualization Panel */}
       <div className="bg-slate-900 rounded-2xl p-8 border border-slate-800 overflow-hidden relative">
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-indigo-900/40 via-slate-900 to-slate-900 pointer-events-none"></div>
            
            <div className="relative z-10">
                <div className="flex items-center gap-4 mb-8">
                    <div className="bg-indigo-500/20 p-2.5 rounded-xl border border-indigo-500/30">
                        <Server className="w-5 h-5 text-indigo-400" />
                    </div>
                    <div>
                        <h3 className="text-lg font-display text-white">Infrastructure Topology</h3>
                        <p className="text-xs text-indigo-200/60 font-mono mt-1">LIVE OBSERVABILITY METRICS</p>
                    </div>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                     
                     {/* 1. App Layer */}
                     <div className="bg-slate-800/50 border border-slate-700/50 p-5 rounded-xl hover:border-slate-600 transition-colors">
                         <h4 className="font-medium text-slate-200 text-sm mb-4 flex items-center justify-between border-b border-slate-700/50 pb-3">
                            <span className="flex items-center"><Box className="w-4 h-4 mr-2" /> Application Edge</span>
                            <span className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.5)]"></span>
                         </h4>
                         <ul className="text-xs text-slate-400 space-y-3 font-mono">
                             <li className="flex items-center justify-between"><span>Container</span> <span className="text-slate-300">Cloud Run</span></li>
                             <li className="flex items-center justify-between"><span>Runtime</span> <span className="text-slate-300">Vite React SPA</span></li>
                             <li className="flex items-center justify-between"><span>Identity</span> <span className="text-slate-300">Firebase IAM</span></li>
                         </ul>
                     </div>

                     {/* 2. Orchestration Layer */}
                     <div className="bg-slate-800/50 border border-slate-700/50 p-5 rounded-xl hover:border-slate-600 transition-colors">
                         <h4 className="font-medium text-slate-200 text-sm mb-4 flex items-center justify-between border-b border-slate-700/50 pb-3">
                            <span className="flex items-center"><Activity className="w-4 h-4 mr-2" /> Action Engine</span>
                            <span className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.5)]"></span>
                         </h4>
                         <ul className="text-xs text-slate-400 space-y-3 font-mono">
                             <li className="flex items-center justify-between"><span>Framework</span> <span className="text-slate-300">Agentic Data Kit</span></li>
                             <li className="flex items-center justify-between"><span>Compute</span> <span className="text-slate-300">Stateless</span></li>
                             <li className="flex items-center justify-between"><span>Toolbox</span> <span className="text-slate-300">MCP Protocol</span></li>
                         </ul>
                     </div>

                     {/* 3. Hybrid Data Layer */}
                     <div className="bg-slate-800/50 border border-slate-700/50 p-5 rounded-xl hover:border-slate-600 transition-colors">
                         <h4 className="font-medium text-slate-200 text-sm mb-4 flex items-center justify-between border-b border-slate-700/50 pb-3">
                            <span className="flex items-center"><Database className="w-4 h-4 mr-2" /> Data Persistence</span>
                            <span className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.5)]"></span>
                         </h4>
                         <ul className="text-xs text-slate-400 space-y-3 font-mono">
                             <li className="flex items-center justify-between"><span>Embeddings</span> <span className="text-slate-300">MongoDB Atlas</span></li>
                             <li className="flex items-center justify-between"><span>Metadata</span> <span className="text-slate-300">Cloud Spanner</span></li>
                             <li className="flex items-center justify-between"><span>Assets</span> <span className="text-slate-300">Cloud Storage</span></li>
                         </ul>
                     </div>

                     {/* 4. AI Context Layer */}
                     <div className="bg-slate-800/50 border border-slate-700/50 p-5 rounded-xl hover:border-slate-600 transition-colors">
                         <h4 className="font-medium text-slate-200 text-sm mb-4 flex items-center justify-between border-b border-slate-700/50 pb-3">
                            <span className="flex items-center"><CheckCircle className="w-4 h-4 mr-2" /> Model Services</span>
                            <span className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.5)]"></span>
                         </h4>
                         <ul className="text-xs text-slate-400 space-y-3 font-mono">
                             <li className="flex items-center justify-between"><span>Core</span> <span className="text-slate-300">Gemini 2.5 Flash</span></li>
                             <li className="flex items-center justify-between"><span>Capabilities</span> <span className="text-slate-300">Multimodal, Tools</span></li>
                             <li className="flex items-center justify-between"><span>Context</span> <span className="text-slate-300">Google Search</span></li>
                         </ul>
                     </div>

                </div>
            </div>
       </div>
    </div>
  );
};

const StatCard: React.FC<{ title: string; value: string; icon: any; color: string; bgColor: string; border: string }> = ({ title, value, icon: Icon, color, bgColor, border }) => (
  <div className={`bg-white dark:bg-slate-900/50 p-6 rounded-2xl border ${border} transition-all`}>
    <div className="flex items-center justify-between mb-4">
      <div className={`p-2.5 rounded-xl ${bgColor} ${color}`}>
        <Icon size={20} strokeWidth={2.5} />
      </div>
      <p className="text-xs font-semibold tracking-wider text-slate-500 uppercase">{title}</p>
    </div>
    <div>
      <h2 className="text-3xl font-display font-medium text-slate-900 dark:text-white mt-1">{value}</h2>
    </div>
  </div>
);

export default Dashboard;
