
import React, { useState, useEffect } from 'react';
import { AnalysisResult, RiskLevel } from '../types';
import { ADKOrchestrator } from '../services/agentSystem';
import { Download, Search, FileText, Filter, Calendar, AlertTriangle, CheckCircle, Eye, RefreshCw, Database, Table, HardDrive } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ReportsProps {
  results: AnalysisResult[]; // Passed from App state, but we can also fetch full history
}

const Reports: React.FC<ReportsProps> = ({ results }) => {
  const [activeTab, setActiveTab] = useState<'audit' | 'inspector'>('audit');
  const [searchTerm, setSearchTerm] = useState('');
  const [filterRisk, setFilterRisk] = useState<string>('ALL');
  const [history, setHistory] = useState<AnalysisResult[]>(results);
  
  // Data Inspector State
  const [dbData, setDbData] = useState<{ spanner: any; mongo: any; sql: any }>({ spanner: [], mongo: 0, sql: 0 });

  // Sync with prop results but also allow fetching full BigQuery history
  useEffect(() => {
    fetchHistory();
    fetchDbStats();
  }, [results, activeTab]);

  const fetchHistory = async () => {
    const data = await ADKOrchestrator.getAuditHistory();
    setHistory(data);
  };

  const fetchDbStats = () => {
      // Direct access to simulated DBs for visualization
      const spannerData = JSON.parse(localStorage.getItem('Spanner_Policies') || '[]');
      const mongoCount = parseInt(localStorage.getItem('Atlas_Vector_Index') || '0');
      const sqlCount = parseInt(localStorage.getItem('Sql_Generic_Data') || '0');
      setDbData({ spanner: spannerData, mongo: mongoCount, sql: sqlCount });
  };

  const filteredResults = history.filter(r => {
    const matchesSearch = 
      r.summary.toLowerCase().includes(searchTerm.toLowerCase()) || 
      r.id.includes(searchTerm) ||
      r.evidenceName.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesRisk = filterRisk === 'ALL' || r.overallRisk === filterRisk;
    return matchesSearch && matchesRisk;
  });

  const generatePDF = (result: AnalysisResult) => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); 
    doc.text("Compliance Analysis Report", 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); 
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 30);
    doc.text(`Report ID: ${result.id}`, 20, 35);
    
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Executive Summary", 20, 50);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Overall Risk Level:`, 20, 60);
    doc.text(result.overallRisk, 60, 60);
    
    doc.text(`Compliance Score:`, 20, 68);
    doc.text(`${result.score}/100`, 60, 68);
    
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const splitSummary = doc.splitTextToSize(result.summary, 170);
    doc.text(splitSummary, 20, 80);

    let yPos = 80 + (splitSummary.length * 5) + 15;

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Detailed Findings", 20, yPos);
    yPos += 10;

    if (result.violations.length === 0) {
        doc.setFontSize(11);
        doc.setTextColor(22, 163, 74); 
        doc.text("No violations detected.", 20, yPos);
    } else {
        result.violations.forEach((v, index) => {
            if (yPos > 260) {
                doc.addPage();
                yPos = 20;
            }
            doc.setFontSize(11);
            doc.setTextColor(185, 28, 28); 
            doc.text(`${index + 1}. Violation [${v.severity}]`, 20, yPos);
            yPos += 6;
            
            doc.setFontSize(10);
            doc.setTextColor(15, 23, 42);
            const desc = doc.splitTextToSize(v.description, 170);
            doc.text(desc, 20, yPos);
            yPos += (desc.length * 5) + 4;
            
            doc.setTextColor(71, 85, 105);
            doc.setFont(undefined, 'bold');
            doc.text("Action:", 20, yPos);
            doc.setFont(undefined, 'normal');
            const rec = doc.splitTextToSize(v.recommendation, 135);
            doc.text(rec, 40, yPos);
            yPos += (rec.length * 5) + 10;
        });
    }
    
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by AI Compliance Copilot", 105, 290, { align: 'center' });
    
    doc.save(`report-${result.id}.pdf`);
  };

  const getRiskBadge = (risk: string) => {
      switch(risk) {
          case 'CRITICAL': return 'bg-red-100 text-red-700 border-red-200';
          case 'HIGH': return 'bg-orange-100 text-orange-700 border-orange-200';
          case 'MEDIUM': return 'bg-amber-100 text-amber-700 border-amber-200';
          case 'LOW': return 'bg-green-100 text-green-700 border-green-200';
          default: return 'bg-slate-100 text-slate-700 border-slate-200';
      }
  };

  return (
    <div className="p-8 max-w-7xl mx-auto animate-in fade-in duration-500">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
            <div>
            <h1 className="text-3xl font-bold text-slate-900">Reports & Data</h1>
            <p className="text-slate-500 mt-2">Audit history and Hybrid Data Layer inspection.</p>
            </div>
            <div className="flex bg-slate-100 p-1 rounded-lg">
                <button 
                    onClick={() => setActiveTab('audit')}
                    className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'audit' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    Audit Logs
                </button>
                <button 
                    onClick={() => setActiveTab('inspector')}
                    className={`px-4 py-2 rounded-md text-sm font-medium transition-all flex items-center ${activeTab === 'inspector' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    <Database className="w-4 h-4 mr-2" /> Data Inspector
                </button>
            </div>
        </div>

        {activeTab === 'audit' ? (
            <>
                {/* Controls */}
                <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200 mb-6 flex flex-col md:flex-row gap-4 justify-between items-center">
                    <div className="relative w-full md:w-96">
                        <Search className="absolute left-3 top-2.5 text-slate-400 w-4 h-4" />
                        <input 
                            type="text" 
                            placeholder="Search logs by ID or summary..." 
                            className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                        />
                    </div>
                    <div className="flex gap-3 w-full md:w-auto">
                        <div className="relative">
                            <Filter className="absolute left-3 top-2.5 text-slate-400 w-4 h-4" />
                            <select 
                                className="pl-9 pr-8 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 appearance-none bg-white cursor-pointer"
                                value={filterRisk}
                                onChange={(e) => setFilterRisk(e.target.value)}
                            >
                                <option value="ALL">All Risks</option>
                                <option value="CRITICAL">Critical</option>
                                <option value="HIGH">High</option>
                                <option value="MEDIUM">Medium</option>
                                <option value="LOW">Low</option>
                            </select>
                        </div>
                        <button onClick={fetchHistory} className="p-2 bg-white border border-slate-200 rounded-lg text-slate-600 hover:text-blue-600 hover:border-blue-200 transition-colors">
                            <RefreshCw className="w-4 h-4" />
                        </button>
                    </div>
                </div>

                {/* Table */}
                <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse">
                            <thead className="bg-slate-50 border-b border-slate-200">
                                <tr>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Date & ID</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Evidence</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Risk Level</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Score</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Summary</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100">
                                {filteredResults.length === 0 ? (
                                    <tr>
                                        <td colSpan={6} className="px-6 py-12 text-center text-slate-500">
                                            <FileText className="w-12 h-12 text-slate-300 mx-auto mb-3" />
                                            <p>No audit records found.</p>
                                        </td>
                                    </tr>
                                ) : (
                                    filteredResults.map((result) => (
                                        <tr key={result.id} className="hover:bg-slate-50 transition-colors">
                                            <td className="px-6 py-4">
                                                <div className="flex flex-col">
                                                    <span className="text-sm font-semibold text-slate-900">
                                                        {new Date(result.timestamp).toLocaleDateString()}
                                                    </span>
                                                    <span className="text-xs text-slate-400 font-mono mt-0.5">#{result.id.slice(-6)}</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4">
                                                <div className="flex items-center">
                                                    <span className="text-sm text-slate-700 capitalize">{result.evidenceType}</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4">
                                                <span className={`px-2.5 py-1 rounded-full text-xs font-bold border ${getRiskBadge(result.overallRisk)}`}>
                                                    {result.overallRisk}
                                                </span>
                                            </td>
                                            <td className="px-6 py-4">
                                                <div className="flex items-center">
                                                    <div className="w-16 h-2 bg-slate-200 rounded-full overflow-hidden mr-2">
                                                        <div 
                                                            className={`h-full rounded-full ${result.score < 70 ? 'bg-red-500' : 'bg-green-500'}`} 
                                                            style={{ width: `${result.score}%` }}
                                                        ></div>
                                                    </div>
                                                    <span className="text-sm font-medium text-slate-600">{result.score}</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 max-w-xs">
                                                <p className="text-sm text-slate-600 truncate" title={result.summary}>
                                                    {result.summary}
                                                </p>
                                            </td>
                                            <td className="px-6 py-4 text-right">
                                                <button 
                                                    onClick={() => generatePDF(result)}
                                                    className="text-blue-600 hover:text-blue-800 p-2 rounded-lg hover:bg-blue-50 transition-colors"
                                                    title="Download PDF"
                                                >
                                                    <Download className="w-4 h-4" />
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </>
        ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-in fade-in duration-300">
                {/* Spanner Inspector */}
                <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col h-[600px]">
                    <div className="p-4 bg-slate-50 border-b border-slate-100 flex items-center justify-between">
                        <h3 className="font-bold text-slate-700 flex items-center">
                            <Table className="w-4 h-4 mr-2 text-blue-600" />
                            Cloud Spanner: Policies
                        </h3>
                        <span className="text-xs bg-slate-200 px-2 py-1 rounded-full text-slate-600">{dbData.spanner.length} Records</span>
                    </div>
                    <div className="flex-1 overflow-auto p-4 font-mono text-xs text-slate-600 bg-slate-900">
                         <pre className="text-green-400">{JSON.stringify(dbData.spanner, null, 2)}</pre>
                    </div>
                </div>

                {/* Generic SQL Inspector */}
                <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col h-[288px]">
                    <div className="p-4 bg-slate-50 border-b border-slate-100 flex items-center justify-between">
                        <h3 className="font-bold text-slate-700 flex items-center">
                            <Database className="w-4 h-4 mr-2 text-orange-600" />
                            SQL (Generic): App Logs
                        </h3>
                        <span className="text-xs bg-slate-200 px-2 py-1 rounded-full text-slate-600">{dbData.sql} Rows</span>
                    </div>
                    <div className="flex-1 flex items-center justify-center p-4 bg-slate-50">
                        <div className="text-center">
                            <Database className="w-12 h-12 text-orange-200 mx-auto mb-2" />
                            <p className="text-slate-500 text-sm">Transactional Logs stored via SQL adapter.</p>
                            <p className="font-bold text-2xl text-slate-700 mt-2">{dbData.sql}</p>
                        </div>
                    </div>
                </div>

                {/* MongoDB Atlas Inspector */}
                <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col h-[288px]">
                    <div className="p-4 bg-slate-50 border-b border-slate-100 flex items-center justify-between">
                        <h3 className="font-bold text-slate-700 flex items-center">
                            <HardDrive className="w-4 h-4 mr-2 text-green-600" />
                            MongoDB Atlas: Vector Store
                        </h3>
                        <span className="text-xs bg-slate-200 px-2 py-1 rounded-full text-slate-600">{dbData.mongo} Embeddings</span>
                    </div>
                    <div className="flex-1 flex items-center justify-center p-4 bg-slate-50">
                         <div className="text-center">
                            <HardDrive className="w-12 h-12 text-green-200 mx-auto mb-2" />
                            <p className="text-slate-500 text-sm">RAG Embeddings generated & indexed.</p>
                            <p className="font-bold text-2xl text-slate-700 mt-2">{dbData.mongo}</p>
                        </div>
                    </div>
                </div>
            </div>
        )}
    </div>
  );
};

export default Reports;
